[package]
name = "rune_remote_brp"
version.workspace = true
edition.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
